

// ------------------------------------------------------------------------------------------------
// This code was generated by EntityFramework Reverse POCO Generator (http://www.reversepoco.com/).
// Created by Simon Hughes (https://about.me/simon.hughes).
//
// Do not make changes directly to this file - edit the template instead.
//
// The following connection settings were used to generate this file:
//     Configuration file:     "Data\App.config"
//     Connection String Name: "AskUsContext"
//     Connection String:      "data source=HMECL001154;initial catalog=AskUs;persist security info=True;user id=sa;password=**zapped**;;MultipleActiveResultSets=True;App=EntityFramework"
// ------------------------------------------------------------------------------------------------
// Database Edition       : Express Edition (64-bit)
// Database Engine Edition: Express

// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Data.AskUs
{
    using System.Linq;

    #region Unit of work

    public interface IAskUsDbContext : System.IDisposable
    {
        System.Data.Entity.DbSet<AnswerComment> AnswerComments { get; set; } // AnswerComment
        System.Data.Entity.DbSet<AnswerStatu> AnswerStatus { get; set; } // AnswerStatus
        System.Data.Entity.DbSet<LawFirm> LawFirms { get; set; } // LawFirm
        System.Data.Entity.DbSet<Question> Questions { get; set; } // Question
        System.Data.Entity.DbSet<QuestionAnswer> QuestionAnswers { get; set; } // QuestionAnswer
        System.Data.Entity.DbSet<QuestionsCategory> QuestionsCategories { get; set; } // QuestionsCategory
        System.Data.Entity.DbSet<QuestionStatu> QuestionStatus { get; set; } // QuestionStatus
        System.Data.Entity.DbSet<ServiceLocation> ServiceLocations { get; set; } // ServiceLocation
        System.Data.Entity.DbSet<User> Users { get; set; } // User
        System.Data.Entity.DbSet<UserRole> UserRoles { get; set; } // UserRole

        int SaveChanges();
        System.Threading.Tasks.Task<int> SaveChangesAsync();
        System.Threading.Tasks.Task<int> SaveChangesAsync(System.Threading.CancellationToken cancellationToken);
        System.Data.Entity.Infrastructure.DbChangeTracker ChangeTracker { get; }
        System.Data.Entity.Infrastructure.DbContextConfiguration Configuration { get; }
        System.Data.Entity.Database Database { get; }
        System.Data.Entity.Infrastructure.DbEntityEntry<TEntity> Entry<TEntity>(TEntity entity) where TEntity : class;
        System.Data.Entity.Infrastructure.DbEntityEntry Entry(object entity);
        System.Collections.Generic.IEnumerable<System.Data.Entity.Validation.DbEntityValidationResult> GetValidationErrors();
        System.Data.Entity.DbSet Set(System.Type entityType);
        System.Data.Entity.DbSet<TEntity> Set<TEntity>() where TEntity : class;
        string ToString();
    }

    #endregion

    #region Database context

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.35.0.0")]
    public class AskUsDbContext : System.Data.Entity.DbContext, IAskUsDbContext
    {
        public System.Data.Entity.DbSet<AnswerComment> AnswerComments { get; set; } // AnswerComment
        public System.Data.Entity.DbSet<AnswerStatu> AnswerStatus { get; set; } // AnswerStatus
        public System.Data.Entity.DbSet<LawFirm> LawFirms { get; set; } // LawFirm
        public System.Data.Entity.DbSet<Question> Questions { get; set; } // Question
        public System.Data.Entity.DbSet<QuestionAnswer> QuestionAnswers { get; set; } // QuestionAnswer
        public System.Data.Entity.DbSet<QuestionsCategory> QuestionsCategories { get; set; } // QuestionsCategory
        public System.Data.Entity.DbSet<QuestionStatu> QuestionStatus { get; set; } // QuestionStatus
        public System.Data.Entity.DbSet<ServiceLocation> ServiceLocations { get; set; } // ServiceLocation
        public System.Data.Entity.DbSet<User> Users { get; set; } // User
        public System.Data.Entity.DbSet<UserRole> UserRoles { get; set; } // UserRole

        static AskUsDbContext()
        {
            System.Data.Entity.Database.SetInitializer<AskUsDbContext>(null);
        }

        public AskUsDbContext()
            : base("Name=AskUsContext")
        {
        }

        public AskUsDbContext(string connectionString)
            : base(connectionString)
        {
        }

        public AskUsDbContext(string connectionString, System.Data.Entity.Infrastructure.DbCompiledModel model)
            : base(connectionString, model)
        {
        }

        public AskUsDbContext(System.Data.Common.DbConnection existingConnection, bool contextOwnsConnection)
            : base(existingConnection, contextOwnsConnection)
        {
        }

        public AskUsDbContext(System.Data.Common.DbConnection existingConnection, System.Data.Entity.Infrastructure.DbCompiledModel model, bool contextOwnsConnection)
            : base(existingConnection, model, contextOwnsConnection)
        {
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
        }

        public bool IsSqlParameterNull(System.Data.SqlClient.SqlParameter param)
        {
            var sqlValue = param.SqlValue;
            var nullableValue = sqlValue as System.Data.SqlTypes.INullable;
            if (nullableValue != null)
                return nullableValue.IsNull;
            return (sqlValue == null || sqlValue == System.DBNull.Value);
        }

        protected override void OnModelCreating(System.Data.Entity.DbModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            modelBuilder.Configurations.Add(new AnswerCommentConfiguration());
            modelBuilder.Configurations.Add(new AnswerStatuConfiguration());
            modelBuilder.Configurations.Add(new LawFirmConfiguration());
            modelBuilder.Configurations.Add(new QuestionConfiguration());
            modelBuilder.Configurations.Add(new QuestionAnswerConfiguration());
            modelBuilder.Configurations.Add(new QuestionsCategoryConfiguration());
            modelBuilder.Configurations.Add(new QuestionStatuConfiguration());
            modelBuilder.Configurations.Add(new ServiceLocationConfiguration());
            modelBuilder.Configurations.Add(new UserConfiguration());
            modelBuilder.Configurations.Add(new UserRoleConfiguration());
        }

        public static System.Data.Entity.DbModelBuilder CreateModel(System.Data.Entity.DbModelBuilder modelBuilder, string schema)
        {
            modelBuilder.Configurations.Add(new AnswerCommentConfiguration(schema));
            modelBuilder.Configurations.Add(new AnswerStatuConfiguration(schema));
            modelBuilder.Configurations.Add(new LawFirmConfiguration(schema));
            modelBuilder.Configurations.Add(new QuestionConfiguration(schema));
            modelBuilder.Configurations.Add(new QuestionAnswerConfiguration(schema));
            modelBuilder.Configurations.Add(new QuestionsCategoryConfiguration(schema));
            modelBuilder.Configurations.Add(new QuestionStatuConfiguration(schema));
            modelBuilder.Configurations.Add(new ServiceLocationConfiguration(schema));
            modelBuilder.Configurations.Add(new UserConfiguration(schema));
            modelBuilder.Configurations.Add(new UserRoleConfiguration(schema));
            return modelBuilder;
        }
    }
    #endregion

    #region Database context factory

    public class AskUsDbContextFactory : System.Data.Entity.Infrastructure.IDbContextFactory<AskUsDbContext>
    {
        public AskUsDbContext Create()
        {
            return new AskUsDbContext();
        }
    }

    #endregion

    #region Fake Database context

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.35.0.0")]
    public class FakeAskUsDbContext : IAskUsDbContext
    {
        public System.Data.Entity.DbSet<AnswerComment> AnswerComments { get; set; }
        public System.Data.Entity.DbSet<AnswerStatu> AnswerStatus { get; set; }
        public System.Data.Entity.DbSet<LawFirm> LawFirms { get; set; }
        public System.Data.Entity.DbSet<Question> Questions { get; set; }
        public System.Data.Entity.DbSet<QuestionAnswer> QuestionAnswers { get; set; }
        public System.Data.Entity.DbSet<QuestionsCategory> QuestionsCategories { get; set; }
        public System.Data.Entity.DbSet<QuestionStatu> QuestionStatus { get; set; }
        public System.Data.Entity.DbSet<ServiceLocation> ServiceLocations { get; set; }
        public System.Data.Entity.DbSet<User> Users { get; set; }
        public System.Data.Entity.DbSet<UserRole> UserRoles { get; set; }

        public FakeAskUsDbContext()
        {
            AnswerComments = new FakeDbSet<AnswerComment>("Id", "Name", "IsActive");
            AnswerStatus = new FakeDbSet<AnswerStatu>("Id", "Name", "IsActive");
            LawFirms = new FakeDbSet<LawFirm>("Id");
            Questions = new FakeDbSet<Question>("Id");
            QuestionAnswers = new FakeDbSet<QuestionAnswer>("Id", "AnswerDescription", "AnswerStatusId", "ParentAnswerId", "FromUserId", "ToUserId", "QuestionId", "Published", "IsActive", "CreatedBy", "CreatedDate");
            QuestionsCategories = new FakeDbSet<QuestionsCategory>("Id", "Name", "IsActive");
            QuestionStatus = new FakeDbSet<QuestionStatu>("Id", "Status", "IsActive", "CreatedBy", "CreatedDate");
            ServiceLocations = new FakeDbSet<ServiceLocation>("Id");
            Users = new FakeDbSet<User>("Id");
            UserRoles = new FakeDbSet<UserRole>("Id", "RoleName", "IsActive", "CreatedBy", "CreatedDate");
        }

        public int SaveChangesCount { get; private set; }
        public int SaveChanges()
        {
            ++SaveChangesCount;
            return 1;
        }

        public System.Threading.Tasks.Task<int> SaveChangesAsync()
        {
            ++SaveChangesCount;
            return System.Threading.Tasks.Task<int>.Factory.StartNew(() => 1);
        }

        public System.Threading.Tasks.Task<int> SaveChangesAsync(System.Threading.CancellationToken cancellationToken)
        {
            ++SaveChangesCount;
            return System.Threading.Tasks.Task<int>.Factory.StartNew(() => 1, cancellationToken);
        }

        protected virtual void Dispose(bool disposing)
        {
        }

        public void Dispose()
        {
            Dispose(true);
        }

        private System.Data.Entity.Infrastructure.DbChangeTracker _changeTracker;
        public System.Data.Entity.Infrastructure.DbChangeTracker ChangeTracker { get { return _changeTracker; } }
        private System.Data.Entity.Infrastructure.DbContextConfiguration _configuration;
        public System.Data.Entity.Infrastructure.DbContextConfiguration Configuration { get { return _configuration; } }
        private System.Data.Entity.Database _database;
        public System.Data.Entity.Database Database { get { return _database; } }
        public System.Data.Entity.Infrastructure.DbEntityEntry<TEntity> Entry<TEntity>(TEntity entity) where TEntity : class
        {
            throw new System.NotImplementedException();
        }
        public System.Data.Entity.Infrastructure.DbEntityEntry Entry(object entity)
        {
            throw new System.NotImplementedException();
        }
        public System.Collections.Generic.IEnumerable<System.Data.Entity.Validation.DbEntityValidationResult> GetValidationErrors()
        {
            throw new System.NotImplementedException();
        }
        public System.Data.Entity.DbSet Set(System.Type entityType)
        {
            throw new System.NotImplementedException();
        }
        public System.Data.Entity.DbSet<TEntity> Set<TEntity>() where TEntity : class
        {
            throw new System.NotImplementedException();
        }
        public override string ToString()
        {
            throw new System.NotImplementedException();
        }

    }

    // ************************************************************************
    // Fake DbSet
    // Implementing Find:
    //      The Find method is difficult to implement in a generic fashion. If
    //      you need to test code that makes use of the Find method it is
    //      easiest to create a test DbSet for each of the entity types that
    //      need to support find. You can then write logic to find that
    //      particular type of entity, as shown below:
    //      public class FakeBlogDbSet : FakeDbSet<Blog>
    //      {
    //          public override Blog Find(params object[] keyValues)
    //          {
    //              var id = (int) keyValues.Single();
    //              return this.SingleOrDefault(b => b.BlogId == id);
    //          }
    //      }
    //      Read more about it here: https://msdn.microsoft.com/en-us/data/dn314431.aspx
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.35.0.0")]
    public class FakeDbSet<TEntity> : System.Data.Entity.DbSet<TEntity>, IQueryable, System.Collections.Generic.IEnumerable<TEntity>, System.Data.Entity.Infrastructure.IDbAsyncEnumerable<TEntity> where TEntity : class
    {
        private readonly System.Reflection.PropertyInfo[] _primaryKeys;
        private readonly System.Collections.ObjectModel.ObservableCollection<TEntity> _data;
        private readonly IQueryable _query;

        public FakeDbSet()
        {
            _data = new System.Collections.ObjectModel.ObservableCollection<TEntity>();
            _query = _data.AsQueryable();
        }

        public FakeDbSet(params string[] primaryKeys)
        {
            _primaryKeys = typeof(TEntity).GetProperties().Where(x => primaryKeys.Contains(x.Name)).ToArray();
            _data = new System.Collections.ObjectModel.ObservableCollection<TEntity>();
            _query = _data.AsQueryable();
        }

        public override TEntity Find(params object[] keyValues)
        {
            if (_primaryKeys == null)
                throw new System.ArgumentException("No primary keys defined");
            if (keyValues.Length != _primaryKeys.Length)
                throw new System.ArgumentException("Incorrect number of keys passed to Find method");

            var keyQuery = this.AsQueryable();
            keyQuery = keyValues
                .Select((t, i) => i)
                .Aggregate(keyQuery,
                    (current, x) =>
                        current.Where(entity => _primaryKeys[x].GetValue(entity, null).Equals(keyValues[x])));

            return keyQuery.SingleOrDefault();
        }

        public override System.Threading.Tasks.Task<TEntity> FindAsync(System.Threading.CancellationToken cancellationToken, params object[] keyValues)
        {
            return System.Threading.Tasks.Task<TEntity>.Factory.StartNew(() => Find(keyValues), cancellationToken);
        }

        public override System.Threading.Tasks.Task<TEntity> FindAsync(params object[] keyValues)
        {
            return System.Threading.Tasks.Task<TEntity>.Factory.StartNew(() => Find(keyValues));
        }

        public override System.Collections.Generic.IEnumerable<TEntity> AddRange(System.Collections.Generic.IEnumerable<TEntity> entities)
        {
            if (entities == null) throw new System.ArgumentNullException("entities");
            var items = entities.ToList();
            foreach (var entity in items)
            {
                _data.Add(entity);
            }
            return items;
        }

        public override TEntity Add(TEntity item)
        {
            if (item == null) throw new System.ArgumentNullException("item");
            _data.Add(item);
            return item;
        }

        public override System.Collections.Generic.IEnumerable<TEntity> RemoveRange(System.Collections.Generic.IEnumerable<TEntity> entities)
        {
            if (entities == null) throw new System.ArgumentNullException("entities");
            var items = entities.ToList();
            foreach (var entity in items)
            {
                _data.Remove(entity);
            }
            return items;
        }

        public override TEntity Remove(TEntity item)
        {
            if (item == null) throw new System.ArgumentNullException("item");
            _data.Remove(item);
            return item;
        }

        public override TEntity Attach(TEntity item)
        {
            if (item == null) throw new System.ArgumentNullException("item");
            _data.Add(item);
            return item;
        }

        public override TEntity Create()
        {
            return System.Activator.CreateInstance<TEntity>();
        }

        public override TDerivedEntity Create<TDerivedEntity>()
        {
            return System.Activator.CreateInstance<TDerivedEntity>();
        }

        public override System.Collections.ObjectModel.ObservableCollection<TEntity> Local
        {
            get { return _data; }
        }

        System.Type IQueryable.ElementType
        {
            get { return _query.ElementType; }
        }

        System.Linq.Expressions.Expression IQueryable.Expression
        {
            get { return _query.Expression; }
        }

        IQueryProvider IQueryable.Provider
        {
            get { return new FakeDbAsyncQueryProvider<TEntity>(_query.Provider); }
        }

        System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator()
        {
            return _data.GetEnumerator();
        }

        System.Collections.Generic.IEnumerator<TEntity> System.Collections.Generic.IEnumerable<TEntity>.GetEnumerator()
        {
            return _data.GetEnumerator();
        }

        System.Data.Entity.Infrastructure.IDbAsyncEnumerator<TEntity> System.Data.Entity.Infrastructure.IDbAsyncEnumerable<TEntity>.GetAsyncEnumerator()
        {
            return new FakeDbAsyncEnumerator<TEntity>(_data.GetEnumerator());
        }
    }

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.35.0.0")]
    public class FakeDbAsyncQueryProvider<TEntity> : System.Data.Entity.Infrastructure.IDbAsyncQueryProvider
    {
        private readonly IQueryProvider _inner;

        public FakeDbAsyncQueryProvider(IQueryProvider inner)
        {
            _inner = inner;
        }

        public IQueryable CreateQuery(System.Linq.Expressions.Expression expression)
        {
            return new FakeDbAsyncEnumerable<TEntity>(expression);
        }

        public IQueryable<TElement> CreateQuery<TElement>(System.Linq.Expressions.Expression expression)
        {
            return new FakeDbAsyncEnumerable<TElement>(expression);
        }

        public object Execute(System.Linq.Expressions.Expression expression)
        {
            return _inner.Execute(expression);
        }

        public TResult Execute<TResult>(System.Linq.Expressions.Expression expression)
        {
            return _inner.Execute<TResult>(expression);
        }

        public System.Threading.Tasks.Task<object> ExecuteAsync(System.Linq.Expressions.Expression expression, System.Threading.CancellationToken cancellationToken)
        {
            return System.Threading.Tasks.Task.FromResult(Execute(expression));
        }

        public System.Threading.Tasks.Task<TResult> ExecuteAsync<TResult>(System.Linq.Expressions.Expression expression, System.Threading.CancellationToken cancellationToken)
        {
            return System.Threading.Tasks.Task.FromResult(Execute<TResult>(expression));
        }
    }

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.35.0.0")]
    public class FakeDbAsyncEnumerable<T> : EnumerableQuery<T>, System.Data.Entity.Infrastructure.IDbAsyncEnumerable<T>, IQueryable<T>
    {
        public FakeDbAsyncEnumerable(System.Collections.Generic.IEnumerable<T> enumerable)
            : base(enumerable)
        { }

        public FakeDbAsyncEnumerable(System.Linq.Expressions.Expression expression)
            : base(expression)
        { }

        public System.Data.Entity.Infrastructure.IDbAsyncEnumerator<T> GetAsyncEnumerator()
        {
            return new FakeDbAsyncEnumerator<T>(this.AsEnumerable().GetEnumerator());
        }

        System.Data.Entity.Infrastructure.IDbAsyncEnumerator System.Data.Entity.Infrastructure.IDbAsyncEnumerable.GetAsyncEnumerator()
        {
            return GetAsyncEnumerator();
        }

        IQueryProvider IQueryable.Provider
        {
            get { return new FakeDbAsyncQueryProvider<T>(this); }
        }
    }

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.35.0.0")]
    public class FakeDbAsyncEnumerator<T> : System.Data.Entity.Infrastructure.IDbAsyncEnumerator<T>
    {
        private readonly System.Collections.Generic.IEnumerator<T> _inner;

        public FakeDbAsyncEnumerator(System.Collections.Generic.IEnumerator<T> inner)
        {
            _inner = inner;
        }

        public void Dispose()
        {
            _inner.Dispose();
        }

        public System.Threading.Tasks.Task<bool> MoveNextAsync(System.Threading.CancellationToken cancellationToken)
        {
            return System.Threading.Tasks.Task.FromResult(_inner.MoveNext());
        }

        public T Current
        {
            get { return _inner.Current; }
        }

        object System.Data.Entity.Infrastructure.IDbAsyncEnumerator.Current
        {
            get { return Current; }
        }
    }

    #endregion

    #region POCO classes

    // AnswerComment
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.35.0.0")]
    public class AnswerComment
    {
        public int Id { get; set; } // Id (Primary key)
        public string Name { get; set; } // Name (Primary key) (length: 50)
        public bool IsActive { get; set; } // IsActive (Primary key)
    }

    // AnswerStatus
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.35.0.0")]
    public class AnswerStatu
    {
        public int Id { get; set; } // Id (Primary key)
        public string Name { get; set; } // Name (Primary key) (length: 50)
        public bool IsActive { get; set; } // IsActive (Primary key)
    }

    // LawFirm
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.35.0.0")]
    public class LawFirm
    {
        public long Id { get; set; } // Id (Primary key)
        public string FirmName { get; set; } // FirmName (length: 100)
        public string EmailId { get; set; } // EmailId (length: 100)
        public string Education { get; set; } // Education (length: 50)
        public int? PictureId { get; set; } // PictureId
        public string EnrollmentNumber { get; set; } // EnrollmentNumber (length: 50)
        public int? Experience { get; set; } // Experience
        public System.DateTime? PracticeStartDate { get; set; } // PracticeStartDate
        public string PracticeCourt { get; set; } // PracticeCourt (length: 50)
        public string BarMember { get; set; } // BarMember (length: 50)
        public string Language { get; set; } // Language (length: 100)
        public string PracticeDescription { get; set; } // PracticeDescription (length: 500)
        public bool? AllowCall { get; set; } // AllowCall
        public bool? AllowWhatsApp { get; set; } // AllowWhatsApp
        public string WhatsAppNumber { get; set; } // WhatsAppNumber (length: 50)
        public bool? AllowEmail { get; set; } // AllowEmail
        public int? ServiceLocationId { get; set; } // ServiceLocationId
        public bool? IsActive { get; set; } // IsActive
        public string CreatedBy { get; set; } // CreatedBy (length: 50)
        public System.DateTime? CreatedDate { get; set; } // CreatedDate
        public string UpdatedBy { get; set; } // UpdatedBy (length: 50)
        public System.DateTime? UpdatedDate { get; set; } // UpdatedDate
    }

    // Question
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.35.0.0")]
    public class Question
    {
        public long Id { get; set; } // Id (Primary key)
        public string Title { get; set; } // Title (length: 500)
        public int? QuestionsCategoryId { get; set; } // QuestionsCategoryId
        public string QuestionDetail { get; set; } // QuestionDetail
        public bool? Notification { get; set; } // Notification
        public bool? GetCall { get; set; } // GetCall
        public string FilePath { get; set; } // FilePath (length: 500)
        public long? UserId { get; set; } // UserId
        public int? StatusId { get; set; } // StatusId
        public int? ServiceLocationId { get; set; } // ServiceLocationId
        public bool? IsActive { get; set; } // IsActive
        public System.DateTime? CreatedDate { get; set; } // CreatedDate
        public string CreatedBy { get; set; } // CreatedBy (length: 50)
        public string UpdatedBy { get; set; } // UpdatedBy (length: 50)
        public System.DateTime? UpdatedDate { get; set; } // UpdatedDate
    }

    // QuestionAnswer
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.35.0.0")]
    public class QuestionAnswer
    {
        public long Id { get; set; } // Id (Primary key)
        public string AnswerTitle { get; set; } // AnswerTitle (length: 50)
        public string AnswerDescription { get; set; } // AnswerDescription (Primary key)
        public int AnswerStatusId { get; set; } // AnswerStatusId (Primary key)
        public int? AnswerCommentId { get; set; } // AnswerCommentId
        public int ParentAnswerId { get; set; } // ParentAnswerId (Primary key)
        public long FromUserId { get; set; } // FromUserId (Primary key)
        public long ToUserId { get; set; } // ToUserId (Primary key)
        public long QuestionId { get; set; } // QuestionId (Primary key)
        public bool Published { get; set; } // Published (Primary key)
        public bool IsActive { get; set; } // IsActive (Primary key)
        public string CreatedBy { get; set; } // CreatedBy (Primary key) (length: 50)
        public System.DateTime CreatedDate { get; set; } // CreatedDate (Primary key)
        public string UpdatedBy { get; set; } // UpdatedBy (length: 50)
        public System.DateTime? UpdatedDate { get; set; } // UpdatedDate
    }

    // QuestionsCategory
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.35.0.0")]
    public class QuestionsCategory
    {
        public int Id { get; set; } // Id (Primary key)
        public string Name { get; set; } // Name (Primary key) (length: 50)
        public bool IsActive { get; set; } // IsActive (Primary key)
        public string CreatedBy { get; set; } // CreatedBy (length: 50)
        public System.DateTime? CreatedDate { get; set; } // CreatedDate
        public string UpdatedBy { get; set; } // UpdatedBy (length: 50)
        public System.DateTime? UpdatedDate { get; set; } // UpdatedDate
    }

    // QuestionStatus
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.35.0.0")]
    public class QuestionStatu
    {
        public int Id { get; set; } // Id (Primary key)
        public string Status { get; set; } // Status (Primary key) (length: 50)
        public bool IsActive { get; set; } // IsActive (Primary key)
        public string CreatedBy { get; set; } // CreatedBy (Primary key) (length: 50)
        public System.DateTime CreatedDate { get; set; } // CreatedDate (Primary key)
    }

    // ServiceLocation
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.35.0.0")]
    public class ServiceLocation
    {
        public int Id { get; set; } // Id (Primary key)
        public string Location { get; set; } // Location (length: 500)
        public string City { get; set; } // City (length: 50)
        public string State { get; set; } // State (length: 50)
        public string Country { get; set; } // Country (length: 50)
        public string Zipcode { get; set; } // Zipcode (length: 50)
        public string IpAddress { get; set; } // IpAddress
    }

    // User
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.35.0.0")]
    public class User
    {
        public long Id { get; set; } // Id (Primary key)
        public string UserName { get; set; } // UserName (length: 50)
        public string Email { get; set; } // Email (length: 100)
        public string Password { get; set; } // Password (length: 50)
        public int? RoleId { get; set; } // RoleId
        public long? LawFirmId { get; set; } // LawFirmId
        public bool? IsActive { get; set; } // IsActive
        public bool? IsDeleted { get; set; } // IsDeleted
        public System.DateTime? CreatedDate { get; set; } // CreatedDate
        public System.DateTime? UpdatedDate { get; set; } // UpdatedDate
    }

    // UserRole
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.35.0.0")]
    public class UserRole
    {
        public int Id { get; set; } // Id (Primary key)
        public string RoleName { get; set; } // RoleName (Primary key) (length: 50)
        public bool IsActive { get; set; } // IsActive (Primary key)
        public string CreatedBy { get; set; } // CreatedBy (Primary key) (length: 50)
        public System.DateTime CreatedDate { get; set; } // CreatedDate (Primary key)
    }

    #endregion

    #region POCO Configuration

    // AnswerComment
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.35.0.0")]
    public class AnswerCommentConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<AnswerComment>
    {
        public AnswerCommentConfiguration()
            : this("dbo")
        {
        }

        public AnswerCommentConfiguration(string schema)
        {
            ToTable("AnswerComment", schema);
            HasKey(x => new { x.Id, x.Name, x.IsActive });

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.Name).HasColumnName(@"Name").HasColumnType("nvarchar").IsRequired().HasMaxLength(50).HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.IsActive).HasColumnName(@"IsActive").HasColumnType("bit").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
        }
    }

    // AnswerStatus
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.35.0.0")]
    public class AnswerStatuConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<AnswerStatu>
    {
        public AnswerStatuConfiguration()
            : this("dbo")
        {
        }

        public AnswerStatuConfiguration(string schema)
        {
            ToTable("AnswerStatus", schema);
            HasKey(x => new { x.Id, x.Name, x.IsActive });

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.Name).HasColumnName(@"Name").HasColumnType("nvarchar").IsRequired().HasMaxLength(50).HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.IsActive).HasColumnName(@"IsActive").HasColumnType("bit").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
        }
    }

    // LawFirm
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.35.0.0")]
    public class LawFirmConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<LawFirm>
    {
        public LawFirmConfiguration()
            : this("dbo")
        {
        }

        public LawFirmConfiguration(string schema)
        {
            ToTable("LawFirm", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("bigint").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.FirmName).HasColumnName(@"FirmName").HasColumnType("nvarchar").IsOptional().HasMaxLength(100);
            Property(x => x.EmailId).HasColumnName(@"EmailId").HasColumnType("nvarchar").IsOptional().HasMaxLength(100);
            Property(x => x.Education).HasColumnName(@"Education").HasColumnType("nvarchar").IsOptional().HasMaxLength(50);
            Property(x => x.PictureId).HasColumnName(@"PictureId").HasColumnType("int").IsOptional();
            Property(x => x.EnrollmentNumber).HasColumnName(@"EnrollmentNumber").HasColumnType("nvarchar").IsOptional().HasMaxLength(50);
            Property(x => x.Experience).HasColumnName(@"Experience").HasColumnType("int").IsOptional();
            Property(x => x.PracticeStartDate).HasColumnName(@"PracticeStartDate").HasColumnType("datetime").IsOptional();
            Property(x => x.PracticeCourt).HasColumnName(@"PracticeCourt").HasColumnType("nvarchar").IsOptional().HasMaxLength(50);
            Property(x => x.BarMember).HasColumnName(@"BarMember").HasColumnType("nvarchar").IsOptional().HasMaxLength(50);
            Property(x => x.Language).HasColumnName(@"Language").HasColumnType("nvarchar").IsOptional().HasMaxLength(100);
            Property(x => x.PracticeDescription).HasColumnName(@"PracticeDescription").HasColumnType("nvarchar").IsOptional().HasMaxLength(500);
            Property(x => x.AllowCall).HasColumnName(@"AllowCall").HasColumnType("bit").IsOptional();
            Property(x => x.AllowWhatsApp).HasColumnName(@"AllowWhatsApp").HasColumnType("bit").IsOptional();
            Property(x => x.WhatsAppNumber).HasColumnName(@"WhatsAppNumber").HasColumnType("nvarchar").IsOptional().HasMaxLength(50);
            Property(x => x.AllowEmail).HasColumnName(@"AllowEmail").HasColumnType("bit").IsOptional();
            Property(x => x.ServiceLocationId).HasColumnName(@"ServiceLocationId").HasColumnType("int").IsOptional();
            Property(x => x.IsActive).HasColumnName(@"IsActive").HasColumnType("bit").IsOptional();
            Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("nvarchar").IsOptional().HasMaxLength(50);
            Property(x => x.CreatedDate).HasColumnName(@"CreatedDate").HasColumnType("datetime").IsOptional();
            Property(x => x.UpdatedBy).HasColumnName(@"UpdatedBy").HasColumnType("nvarchar").IsOptional().HasMaxLength(50);
            Property(x => x.UpdatedDate).HasColumnName(@"UpdatedDate").HasColumnType("datetime").IsOptional();
        }
    }

    // Question
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.35.0.0")]
    public class QuestionConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Question>
    {
        public QuestionConfiguration()
            : this("dbo")
        {
        }

        public QuestionConfiguration(string schema)
        {
            ToTable("Question", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("bigint").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.Title).HasColumnName(@"Title").HasColumnType("nvarchar").IsOptional().HasMaxLength(500);
            Property(x => x.QuestionsCategoryId).HasColumnName(@"QuestionsCategoryId").HasColumnType("int").IsOptional();
            Property(x => x.QuestionDetail).HasColumnName(@"QuestionDetail").HasColumnType("nvarchar(max)").IsOptional();
            Property(x => x.Notification).HasColumnName(@"Notification").HasColumnType("bit").IsOptional();
            Property(x => x.GetCall).HasColumnName(@"GetCall").HasColumnType("bit").IsOptional();
            Property(x => x.FilePath).HasColumnName(@"FilePath").HasColumnType("nvarchar").IsOptional().HasMaxLength(500);
            Property(x => x.UserId).HasColumnName(@"UserId").HasColumnType("bigint").IsOptional();
            Property(x => x.StatusId).HasColumnName(@"StatusId").HasColumnType("int").IsOptional();
            Property(x => x.ServiceLocationId).HasColumnName(@"ServiceLocationId").HasColumnType("int").IsOptional();
            Property(x => x.IsActive).HasColumnName(@"IsActive").HasColumnType("bit").IsOptional();
            Property(x => x.CreatedDate).HasColumnName(@"CreatedDate").HasColumnType("datetime").IsOptional();
            Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("nvarchar").IsOptional().HasMaxLength(50);
            Property(x => x.UpdatedBy).HasColumnName(@"UpdatedBy").HasColumnType("nvarchar").IsOptional().HasMaxLength(50);
            Property(x => x.UpdatedDate).HasColumnName(@"UpdatedDate").HasColumnType("datetime").IsOptional();
        }
    }

    // QuestionAnswer
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.35.0.0")]
    public class QuestionAnswerConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<QuestionAnswer>
    {
        public QuestionAnswerConfiguration()
            : this("dbo")
        {
        }

        public QuestionAnswerConfiguration(string schema)
        {
            ToTable("QuestionAnswer", schema);
            HasKey(x => new { x.Id, x.AnswerDescription, x.AnswerStatusId, x.ParentAnswerId, x.FromUserId, x.ToUserId, x.QuestionId, x.Published, x.IsActive, x.CreatedBy, x.CreatedDate });

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("bigint").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.AnswerTitle).HasColumnName(@"AnswerTitle").HasColumnType("nvarchar").IsOptional().HasMaxLength(50);
            Property(x => x.AnswerDescription).HasColumnName(@"AnswerDescription").HasColumnType("nvarchar(max)").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.AnswerStatusId).HasColumnName(@"AnswerStatusId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.AnswerCommentId).HasColumnName(@"AnswerCommentId").HasColumnType("int").IsOptional();
            Property(x => x.ParentAnswerId).HasColumnName(@"ParentAnswerId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.FromUserId).HasColumnName(@"FromUserId").HasColumnType("bigint").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.ToUserId).HasColumnName(@"ToUserId").HasColumnType("bigint").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.QuestionId).HasColumnName(@"QuestionId").HasColumnType("bigint").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.Published).HasColumnName(@"Published").HasColumnType("bit").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.IsActive).HasColumnName(@"IsActive").HasColumnType("bit").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("nvarchar").IsRequired().HasMaxLength(50).HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.CreatedDate).HasColumnName(@"CreatedDate").HasColumnType("datetime").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.UpdatedBy).HasColumnName(@"UpdatedBy").HasColumnType("nvarchar").IsOptional().HasMaxLength(50);
            Property(x => x.UpdatedDate).HasColumnName(@"UpdatedDate").HasColumnType("datetime").IsOptional();
        }
    }

    // QuestionsCategory
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.35.0.0")]
    public class QuestionsCategoryConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<QuestionsCategory>
    {
        public QuestionsCategoryConfiguration()
            : this("dbo")
        {
        }

        public QuestionsCategoryConfiguration(string schema)
        {
            ToTable("QuestionsCategory", schema);
            HasKey(x => new { x.Id, x.Name, x.IsActive });

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.Name).HasColumnName(@"Name").HasColumnType("nvarchar").IsRequired().HasMaxLength(50).HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.IsActive).HasColumnName(@"IsActive").HasColumnType("bit").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("nvarchar").IsOptional().HasMaxLength(50);
            Property(x => x.CreatedDate).HasColumnName(@"CreatedDate").HasColumnType("datetime").IsOptional();
            Property(x => x.UpdatedBy).HasColumnName(@"UpdatedBy").HasColumnType("nvarchar").IsOptional().HasMaxLength(50);
            Property(x => x.UpdatedDate).HasColumnName(@"UpdatedDate").HasColumnType("datetime").IsOptional();
        }
    }

    // QuestionStatus
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.35.0.0")]
    public class QuestionStatuConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<QuestionStatu>
    {
        public QuestionStatuConfiguration()
            : this("dbo")
        {
        }

        public QuestionStatuConfiguration(string schema)
        {
            ToTable("QuestionStatus", schema);
            HasKey(x => new { x.Id, x.Status, x.IsActive, x.CreatedBy, x.CreatedDate });

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.Status).HasColumnName(@"Status").HasColumnType("nvarchar").IsRequired().HasMaxLength(50).HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.IsActive).HasColumnName(@"IsActive").HasColumnType("bit").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("nvarchar").IsRequired().HasMaxLength(50).HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.CreatedDate).HasColumnName(@"CreatedDate").HasColumnType("datetime").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
        }
    }

    // ServiceLocation
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.35.0.0")]
    public class ServiceLocationConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<ServiceLocation>
    {
        public ServiceLocationConfiguration()
            : this("dbo")
        {
        }

        public ServiceLocationConfiguration(string schema)
        {
            ToTable("ServiceLocation", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.Location).HasColumnName(@"Location").HasColumnType("nvarchar").IsOptional().HasMaxLength(500);
            Property(x => x.City).HasColumnName(@"City").HasColumnType("nvarchar").IsOptional().HasMaxLength(50);
            Property(x => x.State).HasColumnName(@"State").HasColumnType("nvarchar").IsOptional().HasMaxLength(50);
            Property(x => x.Country).HasColumnName(@"Country").HasColumnType("nvarchar").IsOptional().HasMaxLength(50);
            Property(x => x.Zipcode).HasColumnName(@"Zipcode").HasColumnType("nvarchar").IsOptional().HasMaxLength(50);
            Property(x => x.IpAddress).HasColumnName(@"IpAddress").HasColumnType("nvarchar(max)").IsOptional();
        }
    }

    // User
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.35.0.0")]
    public class UserConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<User>
    {
        public UserConfiguration()
            : this("dbo")
        {
        }

        public UserConfiguration(string schema)
        {
            ToTable("User", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("bigint").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.UserName).HasColumnName(@"UserName").HasColumnType("nvarchar").IsOptional().HasMaxLength(50);
            Property(x => x.Email).HasColumnName(@"Email").HasColumnType("nvarchar").IsOptional().HasMaxLength(100);
            Property(x => x.Password).HasColumnName(@"Password").HasColumnType("nvarchar").IsOptional().HasMaxLength(50);
            Property(x => x.RoleId).HasColumnName(@"RoleId").HasColumnType("int").IsOptional();
            Property(x => x.LawFirmId).HasColumnName(@"LawFirmId").HasColumnType("bigint").IsOptional();
            Property(x => x.IsActive).HasColumnName(@"IsActive").HasColumnType("bit").IsOptional();
            Property(x => x.IsDeleted).HasColumnName(@"IsDeleted").HasColumnType("bit").IsOptional();
            Property(x => x.CreatedDate).HasColumnName(@"CreatedDate").HasColumnType("datetime").IsOptional();
            Property(x => x.UpdatedDate).HasColumnName(@"UpdatedDate").HasColumnType("datetime").IsOptional();
        }
    }

    // UserRole
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.35.0.0")]
    public class UserRoleConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<UserRole>
    {
        public UserRoleConfiguration()
            : this("dbo")
        {
        }

        public UserRoleConfiguration(string schema)
        {
            ToTable("UserRole", schema);
            HasKey(x => new { x.Id, x.RoleName, x.IsActive, x.CreatedBy, x.CreatedDate });

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.RoleName).HasColumnName(@"RoleName").HasColumnType("nvarchar").IsRequired().HasMaxLength(50).HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.IsActive).HasColumnName(@"IsActive").HasColumnType("bit").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("nvarchar").IsRequired().HasMaxLength(50).HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.CreatedDate).HasColumnName(@"CreatedDate").HasColumnType("datetime").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
        }
    }

    #endregion

}
// </auto-generated>

